name: CI

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push sur la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow sur les pull requests vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise une machine Ubuntu comme environnement de build

    steps:
    - name: Checkout repository  # Étape pour récupérer le code source
      uses: actions/checkout@v2

    - name: Set up Docker  # Étape pour installer Docker
      uses: docker/setup-buildx-action@v1

    - name: Start Docker Compose  # Étape pour démarrer Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready  # Attendre que les services soient prêts
      run: |
        echo "Waiting for the services to be ready..."
        sleep 30  # Vous pouvez ajuster ce temps en fonction de vos besoins

    - name: Test the web page with curl  # Étape pour tester la page web avec curl
      run: |
        curl -f http://localhost:8080  # Assurez-vous que le port est correct et accessible

    - name: Stop Docker Compose  # Étape pour stopper Docker Compose
      run: docker-compose down
